-- Courier app schema -- fresh-install structure for all 7 tables.
-- Run by install/index.php (step: Database). Safe to re-run: every
-- statement is CREATE TABLE IF NOT EXISTS.
-- Standardized on utf8mb4 throughout for new installs (the columns that
-- pre-date this installer were latin1 in older deployments -- that no
-- longer matters for a fresh database).

CREATE TABLE IF NOT EXISTS `site` (
  `id` int(11) NOT NULL,
  `image` varchar(100) NOT NULL DEFAULT '',
  `image2` varchar(5000) NOT NULL DEFAULT '',
  `name` varchar(100) NOT NULL DEFAULT '',
  `addr` varchar(100) NOT NULL DEFAULT '',
  `phone` varchar(100) NOT NULL DEFAULT '',
  `email` varchar(100) NOT NULL DEFAULT '',
  `addr2` varchar(100) NOT NULL DEFAULT '',
  `phone2` varchar(100) NOT NULL DEFAULT '',
  `email2` varchar(100) NOT NULL DEFAULT '',
  `tawk` varchar(10000) NOT NULL DEFAULT '',
  `year` varchar(100) NOT NULL DEFAULT '',
  `url` varchar(100) NOT NULL DEFAULT '',
  `urlh` varchar(100) NOT NULL DEFAULT '',
  `custom1` varchar(500) NOT NULL DEFAULT '',
  `custom2` varchar(500) NOT NULL DEFAULT '',
  `custom3` varchar(500) NOT NULL DEFAULT '',
  `custom4` varchar(500) NOT NULL DEFAULT '',
  `custom5` varchar(500) NOT NULL DEFAULT '',
  `active_theme` varchar(50) NOT NULL DEFAULT 'theme1',
  `track_color_scheme` varchar(20) NOT NULL DEFAULT 'red',
  `addr3` varchar(100) NOT NULL DEFAULT '',
  `phone3` varchar(100) NOT NULL DEFAULT '',
  `email3` varchar(100) NOT NULL DEFAULT '',
  `addr4` varchar(100) NOT NULL DEFAULT '',
  `phone4` varchar(100) NOT NULL DEFAULT '',
  `email4` varchar(100) NOT NULL DEFAULT '',
  `favicon` varchar(100) NOT NULL DEFAULT '',
  `branch2_name` varchar(100) NOT NULL DEFAULT '',
  `branch3_name` varchar(100) NOT NULL DEFAULT '',
  `branch4_name` varchar(100) NOT NULL DEFAULT '',
  `home_variant` varchar(50) NOT NULL DEFAULT 'courier-service',
  `translate_languages` varchar(255) NOT NULL DEFAULT 'en,fr,es,de,it,pt,ar,zh-CN,ko,ja,ru,hi',
  `translate_source` varchar(10) NOT NULL DEFAULT 'en',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
-- latin1, not utf8mb4: this table has ~35 varchar columns -- utf8mb4's
-- 4-bytes-per-char would push the row past MySQL's 65535-byte row-size
-- limit (confirmed by actually running this against a test DB).

CREATE TABLE IF NOT EXISTS `userlog` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(100) DEFAULT NULL,
  `password` varchar(100) DEFAULT NULL,
  `image` varchar(100) DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL,
  `rank` varchar(50) DEFAULT NULL,
  `cid` varchar(20) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `type` varchar(50) DEFAULT NULL,
  `amt` varchar(50) DEFAULT NULL,
  `rate` varchar(50) DEFAULT NULL,
  `dur` varchar(50) DEFAULT NULL,
  `coldate` varchar(50) DEFAULT NULL,
  `paydate` varchar(50) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `remark` varchar(1000) DEFAULT NULL,
  `loc1` varchar(100) DEFAULT NULL,
  `rank2` varchar(100) DEFAULT NULL,
  `mail2` varchar(50) DEFAULT NULL,
  `phone2` varchar(50) DEFAULT NULL,
  `mail` varchar(50) DEFAULT NULL,
  `paym` varchar(50) DEFAULT NULL,
  `shipm` varchar(50) DEFAULT NULL,
  `comment` varchar(1000) DEFAULT NULL,
  `cdt` varchar(50) DEFAULT NULL,
  `ctm` varchar(50) DEFAULT NULL,
  `cdt2` varchar(50) DEFAULT NULL,
  `ctm2` varchar(50) DEFAULT NULL,
  `status2` varchar(50) DEFAULT NULL,
  `loc2` varchar(50) DEFAULT NULL,
  `car` varchar(100) DEFAULT NULL,
  `carref` varchar(100) DEFAULT NULL,
  `prod` varchar(100) DEFAULT NULL,
  `qty` varchar(100) DEFAULT NULL,
  `frt` varchar(100) DEFAULT NULL,
  `deptim` varchar(100) DEFAULT NULL,
  `pudate` varchar(100) DEFAULT NULL,
  `putm` varchar(100) DEFAULT NULL,
  `pudes` varchar(100) DEFAULT NULL,
  `rmk` varchar(100) DEFAULT NULL,
  `rmk2` varchar(100) DEFAULT NULL,
  `cdt3` varchar(100) DEFAULT NULL,
  `cdt4` varchar(100) DEFAULT NULL,
  `cdt5` varchar(100) DEFAULT NULL,
  `cdt6` varchar(100) DEFAULT NULL,
  `cdt7` varchar(100) DEFAULT NULL,
  `ctm3` varchar(100) DEFAULT NULL,
  `ctm4` varchar(100) DEFAULT NULL,
  `ctm5` varchar(100) DEFAULT NULL,
  `ctm6` varchar(100) DEFAULT NULL,
  `ctm7` varchar(100) DEFAULT NULL,
  `loc3` varchar(100) DEFAULT NULL,
  `loc4` varchar(100) DEFAULT NULL,
  `loc5` varchar(100) DEFAULT NULL,
  `loc6` varchar(100) DEFAULT NULL,
  `loc7` varchar(100) DEFAULT NULL,
  `status3` varchar(100) DEFAULT NULL,
  `status4` varchar(100) DEFAULT NULL,
  `status5` varchar(100) DEFAULT NULL,
  `status6` varchar(100) DEFAULT NULL,
  `status7` varchar(100) DEFAULT NULL,
  `rmk3` varchar(100) DEFAULT NULL,
  `rmk4` varchar(100) DEFAULT NULL,
  `rmk5` varchar(100) DEFAULT NULL,
  `rmk6` varchar(100) DEFAULT NULL,
  `rmk7` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
-- latin1, not utf8mb4: ~60 varchar columns (see the `site` table note above).

CREATE TABLE IF NOT EXISTS `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `image` varchar(100) NOT NULL DEFAULT '',
  `name` varchar(50) DEFAULT NULL,
  `rank` varchar(50) DEFAULT NULL,
  `cid` varchar(20) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `type` varchar(50) DEFAULT NULL,
  `amt` varchar(50) DEFAULT NULL,
  `rate` varchar(50) DEFAULT NULL,
  `dur` varchar(50) DEFAULT NULL,
  `coldate` varchar(50) DEFAULT NULL,
  `paydate` varchar(50) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `remark` varchar(1000) DEFAULT NULL,
  `loc1` varchar(100) DEFAULT NULL,
  `rank2` varchar(100) DEFAULT NULL,
  `mail2` varchar(50) DEFAULT NULL,
  `phone2` varchar(50) DEFAULT NULL,
  `mail` varchar(50) DEFAULT NULL,
  `paym` varchar(50) DEFAULT NULL,
  `shipm` varchar(50) DEFAULT NULL,
  `comment` varchar(1000) DEFAULT NULL,
  `cdt` varchar(50) DEFAULT NULL,
  `ctm` varchar(50) DEFAULT NULL,
  `cdt2` varchar(50) DEFAULT NULL,
  `ctm2` varchar(50) DEFAULT NULL,
  `status2` varchar(50) DEFAULT NULL,
  `loc2` varchar(50) DEFAULT NULL,
  `car` varchar(100) DEFAULT NULL,
  `carref` varchar(100) DEFAULT NULL,
  `prod` varchar(100) DEFAULT NULL,
  `qty` varchar(100) DEFAULT NULL,
  `frt` varchar(100) DEFAULT NULL,
  `deptim` varchar(100) DEFAULT NULL,
  `pudate` varchar(100) DEFAULT NULL,
  `putm` varchar(100) DEFAULT NULL,
  `pudes` varchar(100) DEFAULT NULL,
  `rmk` varchar(100) DEFAULT NULL,
  `rmk2` varchar(100) DEFAULT NULL,
  `cdt3` varchar(100) DEFAULT NULL,
  `cdt4` varchar(100) DEFAULT NULL,
  `cdt5` varchar(100) DEFAULT NULL,
  `cdt6` varchar(100) DEFAULT NULL,
  `cdt7` varchar(100) DEFAULT NULL,
  `ctm3` varchar(100) DEFAULT NULL,
  `ctm4` varchar(100) DEFAULT NULL,
  `ctm5` varchar(100) DEFAULT NULL,
  `ctm6` varchar(100) DEFAULT NULL,
  `ctm7` varchar(100) DEFAULT NULL,
  `loc3` varchar(100) DEFAULT NULL,
  `loc4` varchar(100) DEFAULT NULL,
  `loc5` varchar(100) DEFAULT NULL,
  `loc6` varchar(100) DEFAULT NULL,
  `loc7` varchar(100) DEFAULT NULL,
  `status3` varchar(100) DEFAULT NULL,
  `status4` varchar(100) DEFAULT NULL,
  `status5` varchar(100) DEFAULT NULL,
  `status6` varchar(100) DEFAULT NULL,
  `status7` varchar(100) DEFAULT NULL,
  `rmk3` varchar(100) DEFAULT NULL,
  `rmk4` varchar(100) DEFAULT NULL,
  `rmk5` varchar(100) DEFAULT NULL,
  `rmk6` varchar(100) DEFAULT NULL,
  `rmk7` varchar(100) DEFAULT NULL,
  `rrr` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_cid` (`cid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
-- latin1, not utf8mb4: ~60 varchar columns (see the `site` table note above).

CREATE TABLE IF NOT EXISTS `mail_settings` (
  `id` tinyint(3) unsigned NOT NULL DEFAULT 1,
  `smtp_host` varchar(191) NOT NULL DEFAULT '',
  `smtp_port` smallint(5) unsigned NOT NULL DEFAULT 587,
  `smtp_encryption` varchar(10) NOT NULL DEFAULT 'tls',
  `smtp_username` varchar(191) NOT NULL DEFAULT '',
  `smtp_password_enc` text DEFAULT NULL,
  `smtp_from_email` varchar(191) NOT NULL DEFAULT '',
  `smtp_from_name` varchar(191) NOT NULL DEFAULT '',
  `smtp_reply_to` varchar(191) NOT NULL DEFAULT '',
  `bcc_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `bcc_email` varchar(191) NOT NULL DEFAULT '',
  `notify_on_create` tinyint(1) NOT NULL DEFAULT 1,
  `notify_on_status_update` tinyint(1) NOT NULL DEFAULT 1,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `email_templates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `template_key` varchar(64) NOT NULL,
  `name` varchar(191) NOT NULL,
  `description` varchar(255) NOT NULL DEFAULT '',
  `subject` varchar(255) NOT NULL,
  `html_body` mediumtext NOT NULL,
  `text_body` mediumtext NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `template_key` (`template_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `email_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `template_key` varchar(64) NOT NULL DEFAULT '',
  `recipient_email` varchar(191) NOT NULL,
  `recipient_name` varchar(191) NOT NULL DEFAULT '',
  `subject` varchar(255) NOT NULL DEFAULT '',
  `html_body` mediumtext NOT NULL,
  `text_body` mediumtext NOT NULL,
  `status` enum('sent','failed') NOT NULL,
  `error_message` varchar(500) NOT NULL DEFAULT '',
  `tracking_number` varchar(64) NOT NULL DEFAULT '',
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `login_attempts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `identifier` varchar(191) NOT NULL,
  `attempts` int(11) NOT NULL DEFAULT 1,
  `first_attempt_at` datetime NOT NULL,
  `locked_until` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_identifier` (`identifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
